### ISSUE TITLE
Añadir ejemplos sencillos de conceptos en Rust a través de los comandos del Bot

### ISSUE THREAD

**Issue by CrawKatt** [RustLangES/cangrebot#12]
Sugiero crear un comando rust que tome todos los conceptos posibles del lenguaje y de una descripción sencilla y un ejemplo de código. Para una descripción más detallada se podría poner un link al libro de Rust traducido al Español.

Dejaré un ejemplo de mi Bot que ya posee esa característica:
![example](https://github.com/RustLangES/cangrebot/assets/108593932/0bbbe330-b002-4ad6-8aa6-a87a09dd9a2a)

**Comment by SergioRibera** [comment]
Esto ya esta implementado, no?

**Comment by CrawKatt** [comment]
> Esto ya esta implementado, no?

Si, hace tiempo fue implementado utilizando un repo con los ejemplos
