### ISSUE TITLE
Comando: Sugerencias

### ISSUE THREAD

**Issue by dsolartec** [RustLangES/cangrebot#5]
# Descripción
Con este comando se pretende enviar una sugerencia al canal de #sugerencias (ID: `824695624665923594`).

# Formato
Puede enviarse usando un embed:
```json
{
  "título": "Sugerencia",
  "descripción": "Mensaje de la sugerencia\r\n\r\n- Sugerido por: @mención"
}
```

Ejecución del comando:
```
{prefijo}sugerencia {mensaje}
```

**Comment by shiftrtech** [comment]
Esto no lo entiendo, si escribo el comando debería enviar un mensaje al canal sugerencias con el @ del usuario que lo envío?, para que es el embed?

**Comment by danielsolartech** [comment]
> Esto no lo entiendo, si escribo el comando debería enviar un mensaje al canal sugerencias con el @ del usuario que lo envío?, para que es el embed?

El embed es para mandarlo al canal.

Algo así: [https://prnt.sc/11ptyfa](https://prnt.sc/11ptyfa)

**Comment by SergioRibera** [comment]
Comando implementado
